### PR TITLE
Update dependencies and SDK

### PR DESCRIPTION
**Pull request by kvuj**

### CODE REVIEW

**Comment by kvuj** [comment]
uhh........ wut

```
"build-commands": [
        "cp bin/pandoc /app/bin/pandoc",
        "cp bin/pandoc-citeproc /app/bin/pandoc-citeproc"
      ],
```

**Comment by kvuj** [comment]
Also
`--env=PATH=/app/bin:/usr/bin:/app/extensions/TexLive/2018/bin/x86_64-linux/`
is arch dependent, but I'm not sure how/why it exists, so maybe somebody else could help.

**Comment by kvuj** [comment]
@somas95 Pandoc removed pandoc-citeproc from their binaries so I removed it from the build. Is it necessary for this app to work?

**Comment by somas95** [comment]
Hi, @kvuj , thanks for looking into this

I already removed pandoc-citeproc from the beta manifest: https://github.com/flathub/org.gnome.gitlab.somas.Apostrophe/blob/beta/org.gnome.gitlab.somas.Apostrophe.json, which I planed to merge into master this coming week. Regarding how I compile pandoc, I think you're right. We can move to the beta channel to betatest these changes if you want. Proper multiarch support would be great

**Comment by kvuj** [comment]
Alright, in the beta channel, it seems perfect except for gspell being a bit old and some python deps being a bit out of date.

Meanwhile, if you want, I'll look into making it arch independent and submitting it to beta.

**Pull request closed without merging**
